/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'guy' at '4/25/17 1:25 PM' with Gradle 2.14.1
 *
 * @author guy, @date 4/25/17 1:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
